package project4;

import jakarta.servlet.http.HttpServlet;


import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
public class cartmethods extends HttpServlet {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public  void service(HttpServletRequest req,HttpServletResponse res) throws IOException {
    String email= req.getParameter("email");
    String name= req.getParameter("name");
    String address= req.getParameter("address");
    String phone= req.getParameter("phone");
    String checkbox=req.getParameter("gender");
    String imagesrc;
    System.out.print(checkbox);
    if (checkbox.equals("1")){
    	 imagesrc="images\\jazzcash.png ";
    }
    else if(checkbox.equals("2")) {
    	 imagesrc="images\\cash1.png ";
    }
    else {
    	imagesrc="images\\mastercard.png ";
    }
  
    PrintWriter out= res.getWriter();
    
    out.print("<!DOCTYPE html>\r\n"
    		+ "<html>\r\n"
    		+ "<head>\r\n"
    		+ "<title>Elite Shoppy</title>\r\n"
    		+ "<!--/tags -->\r\n"
    		+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
    		+ "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
    		+ "<meta name=\"keywords\" content=\"Elite Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n"
    		+ "Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n"
    		+ "<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n"
    		+ "        function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n"
    		+ "<!--//tags -->\r\n"
    		+ "<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n"
    		+ "<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n"
    		+ "<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n"
    		+ "<link href=\"css/easy-responsive-tabs.css\" rel='stylesheet' type='text/css'/>\r\n"
    		+ "<!-- //for bootstrap working -->\r\n"
    		+ "<link href=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800\" rel=\"stylesheet\">\r\n"
    		+ "<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>\r\n"
    		+ "<!-- CHAT-BOT-->\r\n"
    		+ "    <meta charset=\"UTF-8\">\r\n"
    		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
    		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
    		+ "    <title>Chat Bot</title>\r\n"
    		+ "\r\n"
    		+ "    <link rel=\"stylesheet\" href=\"static/css/chat.css\">\r\n"
    		+ "    <link rel=\"stylesheet\" href=\"static/css/home.css\">\r\n"
    		+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
    		+ "<!--/tags -->\r\n"
    		+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
    		+ "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
    		+ "<meta name=\"keywords\" content=\"Elite Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n"
    		+ "Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n"
    		+ "<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n"
    		+ "        function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n"
    		+ "<!--//tags -->\r\n"
    		+ "<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n"
    		+ "<link href=\"css/team.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n"
    		+ "<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n"
    		+ "<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n"
    		+ "<!--===============================================================================================-->  \r\n"
    		+ "    <link rel=\"icon\" type=\"image/png\" href=\"images/icons/favicon.ico\"/>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/Linearicons-Free-v1.0.0/icon-font.min.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n"
    		+ "<!--===============================================================================================-->  \r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animsition/css/animsition.min.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/select2/select2.min.css\">\r\n"
    		+ "<!--===============================================================================================-->  \r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/daterangepicker/daterangepicker.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n"
    		+ "    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "<!-- //for bootstrap working -->\r\n"
    		+ "<link href=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800\" rel=\"stylesheet\">\r\n"
    		+ "<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>\r\n"
    		+ "    <!-- CHAT-BOT-->\r\n"
    		+ "    <meta charset=\"UTF-8\">\r\n"
    		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
    		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
    		+ "    <title>Chat Bot</title>\r\n"
    		+ "\r\n"
    		+ "    <link rel=\"stylesheet\" href=\"static/css/chat.css\">\r\n"
    		+ "    <link rel=\"stylesheet\" href=\"static/css/home.css\">\r\n"
    		+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
    		+ "</head>\r\n"
    		+ "</head>\r\n"
    		+ "<body>\r\n"
    		+ "     <!-- CHAT BAR BLOCK -->\r\n"
    		+ "    <div class=\"chat-bar-collapsible\">\r\n"
    		+ "        <button id=\"chat-button\" type=\"button\" class=\"collapsible\">Chat with us!\r\n"
    		+ "            <i id=\"chat-icon\" style=\"color: #fff;\" class=\"fa fa-fw fa-comments-o\"></i>\r\n"
    		+ "        </button>\r\n"
    		+ "\r\n"
    		+ "        <div class=\"content\">\r\n"
    		+ "            <div class=\"full-chat-block\">\r\n"
    		+ "                <!-- Message Container -->\r\n"
    		+ "                <div class=\"outer-container\">\r\n"
    		+ "                    <div class=\"chat-container\">\r\n"
    		+ "                        <!-- Messages -->\r\n"
    		+ "                        <div id=\"chatbox\">\r\n"
    		+ "                            <h5 id=\"chat-timestamp\"></h5>\r\n"
    		+ "                            <p id=\"botStarterMessage\" class=\"botText\"><span>Loading...</span></p>\r\n"
    		+ "                        </div>\r\n"
    		+ "\r\n"
    		+ "                        <!-- User input box -->\r\n"
    		+ "                        <div class=\"chat-bar-input-block\">\r\n"
    		+ "                            <div id=\"userInput\">\r\n"
    		+ "                                <input id=\"textInput\" class=\"input-box\" type=\"text\" name=\"msg\"\r\n"
    		+ "                                    placeholder=\"Tap 'Enter' to send a message\">\r\n"
    		+ "                                <p></p>\r\n"
    		+ "                            </div>\r\n"
    		+ "\r\n"
    		+ "                            <div class=\"chat-bar-icons\">\r\n"
    		+ "                                <i id=\"chat-icon\" style=\"color: crimson;\" class=\"fa fa-fw fa-heart\"\r\n"
    		+ "                                    onclick=\"heartButton()\"></i>\r\n"
    		+ "                                <i id=\"chat-icon\" style=\"color: #333;\" class=\"fa fa-fw fa-send\"\r\n"
    		+ "                                    onclick=\"sendButton()\"></i>\r\n"
    		+ "                            </div>\r\n"
    		+ "                        </div>\r\n"
    		+ "\r\n"
    		+ "                        <div id=\"chat-bar-bottom\">\r\n"
    		+ "                            <p></p>\r\n"
    		+ "                        </div>\r\n"
    		+ "\r\n"
    		+ "                    </div>\r\n"
    		+ "                </div>\r\n"
    		+ "\r\n"
    		+ "            </div>\r\n"
    		+ "        </div>\r\n"
    		+ "\r\n"
    		+ "    </div>\r\n"
    		+ "<!-- header -->\r\n"
    		+ "<div class=\"header\" id=\"home\">\r\n"
    		+ "    <div class=\"container\">\r\n"
    		+ "        <ul>\r\n"
    		+ "            <li> <a href=\"login.html\" ><i class=\"fa fa-unlock-alt\" aria-hidden=\"true\"></i> Sign In </a></li>\r\n"
    		+ "            <li> <a href=\"signup.html\" ><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Sign Up </a></li>\r\n"
    		+ "            <li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i> Call : +92 3305873725</li>\r\n"
    		+ "            <li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i> <a href=\"mailto:info@example.com\">Eliteshoppy@gmail.com</a></li>\r\n"
    		+ "        </ul>\r\n"
    		+ "    </div>\r\n"
    		+ "</div>\r\n"
    		+ "<!-- //header -->\r\n"
    		+ "<!-- header-bot -->\r\n"
    		+ "<div class=\"header-bot\">\r\n"
    		+ "    <div class=\"header-bot_inner_wthreeinfo_header_mid\">\r\n"
    		+ "        <div class=\"col-md-4 header-middle\">\r\n"
    		+ "            <form action=\"#\" method=\"post\">\r\n"
    		+ "                    <input type=\"search\" name=\"search\" placeholder=\"Search here...\" required=\"\">\r\n"
    		+ "                    <input type=\"submit\" value=\" \">\r\n"
    		+ "                <div class=\"clearfix\"></div>\r\n"
    		+ "            </form>\r\n"
    		+ "        </div>\r\n"
    		+ "        <!-- header-bot -->\r\n"
    		+ "            <div class=\"col-md-4 logo_agile\">\r\n"
    		+ "                <h1><a href=\"index.html\"><span>E</span>lite Shoppy <i class=\"fa fa-shopping-bag top_logo_agile_bag\" aria-hidden=\"true\"></i></a></h1>\r\n"
    		+ "            </div>\r\n"
    		+ "\r\n"
    		+ "        <!-- header-bot \r\n"
    		+ "        <div class=\"col-md-4 agileits-social top_content\">\r\n"
    		+ "                        <ul class=\"social-nav model-3d-0 footer-social w3_agile_social\">\r\n"
    		+ "                                                           <li class=\"share\">Share On : </li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"facebook\">\r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"twitter\"> \r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"instagram\">\r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"pinterest\">\r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                        </ul>\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "        </div>-->\r\n"
    		+ "        <div style=\"position: relative;left: 250px\">\r\n"
    		+ "            <span>Shahab Ali</span>\r\n"
    		+ "            <span>\r\n"
    		+ "                <button style=\"border-radius:50px;border:none;background-color: white\">\r\n"
    		+ "                    <img src=\"images\\t2.jpg\" alt=\"Login pic\" width = \"50\" height=\"50\" style=\"border-radius: 50px;\">\r\n"
    		+ "                </button>\r\n"
    		+ "            </span>\r\n"
    		+ "        </div>\r\n"
    		+ "        <div class=\"clearfix\"></div>\r\n"
    		+ "    </div>\r\n"
    		+ "</div>\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "<div style=\"padding-left: 400px;\" class=\"limiter\">\r\n"
    		+ "        <div class=\"container-login100\">\r\n"
    		+ "          <!--  <div class=\"login100-more\" style=\"background-image: url('images/cart.png');\"></div>  --> \r\n"
    		+ "\r\n"
    		+ "            <div class=\"wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50\">\r\n"
    		+ "              "
    		+ "                    <span class=\"login100-form-title p-b-59\">\r\n"
    		+ "                        Shipping Details\r\n"
    		+ "                    </span>\r\n"
    		+ "\r\n"
    		+ "                    <div class=\"wrap-input100 validate-input\" data-validate=\"Name is required\">\r\n"
    		+ "                        <span >Full Name</span>\r\n"
    		+ "                        <p>"+name+"</p>\r\n"
    		+ "                       \r\n"
    		+ "                    </div>\r\n"
    		+ "\r\n"
    		+ "                    <div class=\"wrap-input100 validate-input\" data-validate = \"Valid email is required: ex@abc.xyz\">\r\n"
    		+ "                        <span>Email</span>\r\n"
    		+ "                        <p>"+email+"</p>\r\n"
    		+ "                        \r\n"
    		+ "                    </div>\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "                    \r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "                    <div class=\"wrap-input100 validate-input\" data-validate=\"Username is required\">\r\n"
    		+ "                        <span >Address</span>\r\n"
    		+ "                        <p>"+address+"</p>\r\n"
    		+ "                        \r\n"
    		+ "                    </div>\r\n"
    		+ "\r\n"
    		+ "                    <div class=\"wrap-input100 validate-input\" data-validate=\"Username is required\">\r\n"
    		+ "                        <span >Phone Number</span>\r\n"
    		+ "                        <p>"+phone+"</p>\r\n"
    		+ "\r\n"
    		+ "                      \r\n"
    		+ "                    </div>\r\n"
    		+ "                    <div class=\"wrap-input100 validate-input\" data-validate = \"Password is required\">\r\n"
    		+ "                        <p >Payment option</p>\r\n"
    		+ "                       <img src="+imagesrc+">\r\n"
    		+ "                    </div>\r\n"
    		+ "                    <div class=\"wrap-login100-form-btn\">\r\n"
    		+ "                            <div class=\"login100-form-bgbtn\"></div>\r\n"
    		+ "                            <a href=\"confirmationpage.html\" style=\"color: white;\"><button class=\"login100-form-btn\">\r\n"
    		+ "                                Confirm Order\r\n"
    		+ "                            </button></a>\r\n"
    		+ "                        </div>\r\n"
    		+ "\r\n"
    		+ "                        <a href=\"confirmationpage.html\" class=\"dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30\">\r\n"
    		+ "                            Proceed\r\n"
    		+ "                            <i class=\"fa fa-long-arrow-right m-l-5\"></i>\r\n"
    		+ "                        </a>\r\n"
    		+ "                    </div>\r\n"
    		+ "\r\n"
    		+ "                \r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "                \r\n"
    		+ "            </div>\r\n"
    		+ "        </div>\r\n"
    		+ "    </div>\r\n"
    		+ "    <!--===============================================================================================-->\r\n"
    		+ "    <script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <script src=\"vendor/animsition/js/animsition.min.js\"></script>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <script src=\"vendor/bootstrap/js/popper.js\"></script>\r\n"
    		+ "    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <script src=\"vendor/select2/select2.min.js\"></script>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <script src=\"vendor/daterangepicker/moment.min.js\"></script>\r\n"
    		+ "    <script src=\"vendor/daterangepicker/daterangepicker.js\"></script>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <script src=\"vendor/countdowntime/countdowntime.js\"></script>\r\n"
    		+ "<!--===============================================================================================-->\r\n"
    		+ "    <script src=\"js/main.js\"></script>\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "\r\n"
    		+ "<!--footer-->\r\n"
    		+ "<div class=\"footer\">\r\n"
    		+ "    <div class=\"footer_agile_inner_info_w3l\">\r\n"
    		+ "        <div class=\"col-md-3 footer-left\">\r\n"
    		+ "            <h2><a href=\"index.html\"><span>E</span>lite Shoppy </a></h2>\r\n"
    		+ "            <p>Welcome to the official store of Elite Shoppy. Elite delivers the wide range of innovative and premium quality products.</p>\r\n"
    		+ "            <ul class=\"social-nav model-3d-0 footer-social w3_agile_social two\">\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"facebook\">\r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"twitter\"> \r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"instagram\">\r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                            <li><a href=\"#\" class=\"pinterest\">\r\n"
    		+ "                                                                  <div class=\"front\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></div>\r\n"
    		+ "                                                                  <div class=\"back\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></div></a></li>\r\n"
    		+ "                                                        </ul>\r\n"
    		+ "        </div>\r\n"
    		+ "        <div class=\"col-md-9 footer-right\">\r\n"
    		+ "            <div class=\"sign-grds\">\r\n"
    		+ "                <div class=\"col-md-4 sign-gd\">\r\n"
    		+ "                    <h4>Our <span>Information</span> </h4>\r\n"
    		+ "                    <ul>\r\n"
    		+ "                        <li><a href=\"index.html\">Home</a></li>\r\n"
    		+ "                        <li><a href=\"mens.html\">Men's Wear</a></li>\r\n"
    		+ "                        <li><a href=\"womens.html\">Women's wear</a></li>\r\n"
    		+ "                        <li><a href=\"about.html\">About</a></li>\r\n"
    		+ "                        <!--<li><a href=\"typography.html\">Short Codes</a></li>-->\r\n"
    		+ "                        <li><a href=\"contact.html\">Contact</a></li>\r\n"
    		+ "                    </ul>\r\n"
    		+ "                </div>\r\n"
    		+ "                \r\n"
    		+ "                <div class=\"col-md-5 sign-gd-two\">\r\n"
    		+ "                    <h4>Store <span>Information</span></h4>\r\n"
    		+ "                    <div class=\"w3-address\">\r\n"
    		+ "                        <div class=\"w3-address-grid\">\r\n"
    		+ "                            <div class=\"w3-address-left\">\r\n"
    		+ "                                <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\r\n"
    		+ "                            </div>\r\n"
    		+ "                            <div class=\"w3-address-right\">\r\n"
    		+ "                                <h6>Phone Number</h6>\r\n"
    		+ "                                <p>+92 3305873725</p>\r\n"
    		+ "                            </div>\r\n"
    		+ "                            <div class=\"clearfix\"> </div>\r\n"
    		+ "                        </div>\r\n"
    		+ "                        <div class=\"w3-address-grid\">\r\n"
    		+ "                            <div class=\"w3-address-left\">\r\n"
    		+ "                                <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n"
    		+ "                            </div>\r\n"
    		+ "                            <div class=\"w3-address-right\">\r\n"
    		+ "                                <h6>Email Address</h6>\r\n"
    		+ "                                <p>Email :<a href=\"mailto:example@email.com\"> ahmedali_45@gmail.com</a></p>\r\n"
    		+ "                            </div>\r\n"
    		+ "                            <div class=\"clearfix\"> </div>\r\n"
    		+ "                        </div>\r\n"
    		+ "                        <div class=\"w3-address-grid\">\r\n"
    		+ "                            <div class=\"w3-address-left\">\r\n"
    		+ "                                <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\r\n"
    		+ "                            </div>\r\n"
    		+ "                            <div class=\"w3-address-right\">\r\n"
    		+ "                                <h6>Location</h6>\r\n"
    		+ "                                <p>Shop #213, First Floor, Giga Mall, Islamabad.\r\n"
    		+ "                                \r\n"
    		+ "                                </p>\r\n"
    		+ "                            </div>\r\n"
    		+ "                            <div class=\"clearfix\"> </div>\r\n"
    		+ "                        </div>\r\n"
    		+ "                    </div>\r\n"
    		+ "                </div>\r\n"
    		+ "                <div class=\"col-md-3 sign-gd flickr-post\">\r\n"
    		+ "                    <h4>Flickr <span>Posts</span></h4>\r\n"
    		+ "                    <ul>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t1.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t2.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t3.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t4.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t1.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t2.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t3.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t2.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                        <li><a href=\"single.html\"><img src=\"images/t4.jpg\" alt=\" \" class=\"img-responsive\" /></a></li>\r\n"
    		+ "                    </ul>\r\n"
    		+ "                </div>\r\n"
    		+ "                <div class=\"clearfix\"></div>\r\n"
    		+ "            </div>\r\n"
    		+ "        </div>\r\n"
    		+ "        <div class=\"clearfix\"></div>\r\n"
    		+ "            <div class=\"agile_newsletter_footer\">\r\n"
    		+ "                    <div class=\"col-sm-6 newsleft\">\r\n"
    		+ "                <h3>SIGN UP FOR NEWSLETTER !</h3>\r\n"
    		+ "            </div>\r\n"
    		+ "            <div class=\"col-sm-6 newsright\">\r\n"
    		+ "                <form action=\"#\" method=\"post\">\r\n"
    		+ "                    <input type=\"email\" placeholder=\"Enter your email...\" name=\"email\" required=\"\">\r\n"
    		+ "                    <input type=\"submit\" value=\"Submit\">\r\n"
    		+ "                </form>\r\n"
    		+ "            </div>\r\n"
    		+ "\r\n"
    		+ "        <div class=\"clearfix\"></div>\r\n"
    		+ "    </div>\r\n"
    		+ "        <p class=\"copy-right\">&copy 2021 Elite shoppy. All rights reserved | Design by <a href=\"#\"><!--AUJ-->BESE</a></p>\r\n"
    		+ "    </div>\r\n"
    		+ "</div>\r\n"
    		+ "<!-- //footer -->\r\n"
    		+ "\r\n"
    		+ "<!-- login -->\r\n"
    		+ "            <div class=\"modal fade\" id=\"myModal4\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n"
    		+ "                <div class=\"modal-dialog\" role=\"document\">\r\n"
    		+ "                    <div class=\"modal-content modal-info\">\r\n"
    		+ "                        <div class=\"modal-header\">\r\n"
    		+ "                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>                        \r\n"
    		+ "                        </div>\r\n"
    		+ "                        <div class=\"modal-body modal-spa\">\r\n"
    		+ "                            <div class=\"login-grids\">\r\n"
    		+ "                                <div class=\"login\">\r\n"
    		+ "                                    <div class=\"login-bottom\">\r\n"
    		+ "                                        <h3>Sign up for free</h3>\r\n"
    		+ "                                        <form>\r\n"
    		+ "                                            <div class=\"sign-up\">\r\n"
    		+ "                                                <h4>Email :</h4>\r\n"
    		+ "                                                <input type=\"text\" value=\"Type here\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Type here';}\" required=\"\"> \r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            <div class=\"sign-up\">\r\n"
    		+ "                                                <h4>Password :</h4>\r\n"
    		+ "                                                <input type=\"password\" value=\"Password\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Password';}\" required=\"\">\r\n"
    		+ "                                                \r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            <div class=\"sign-up\">\r\n"
    		+ "                                                <h4>Re-type Password :</h4>\r\n"
    		+ "                                                <input type=\"password\" value=\"Password\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Password';}\" required=\"\">\r\n"
    		+ "                                                \r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            <div class=\"sign-up\">\r\n"
    		+ "                                                <input type=\"submit\" value=\"REGISTER NOW\" >\r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            \r\n"
    		+ "                                        </form>\r\n"
    		+ "                                    </div>\r\n"
    		+ "                                    <div class=\"login-right\">\r\n"
    		+ "                                        <h3>Sign in with your account</h3>\r\n"
    		+ "                                        <form>\r\n"
    		+ "                                            <div class=\"sign-in\">\r\n"
    		+ "                                                <h4>Email :</h4>\r\n"
    		+ "                                                <input type=\"text\" value=\"Type here\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Type here';}\" required=\"\"> \r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            <div class=\"sign-in\">\r\n"
    		+ "                                                <h4>Password :</h4>\r\n"
    		+ "                                                <input type=\"password\" value=\"Password\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Password';}\" required=\"\">\r\n"
    		+ "                                                <a href=\"#\">Forgot password?</a>\r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            <div class=\"single-bottom\">\r\n"
    		+ "                                                <input type=\"checkbox\"  id=\"brand\" value=\"\">\r\n"
    		+ "                                                <label for=\"brand\"><span></span>Remember Me.</label>\r\n"
    		+ "                                            </div>\r\n"
    		+ "                                            <div class=\"sign-in\">\r\n"
    		+ "                                                <input type=\"submit\" value=\"SIGNIN\" >\r\n"
    		+ "                                            </div>\r\n"
    		+ "                                        </form>\r\n"
    		+ "                                    </div>\r\n"
    		+ "                                    <div class=\"clearfix\"></div>\r\n"
    		+ "                                </div>\r\n"
    		+ "                                <p>By logging in you agree to our <a href=\"#\">Terms and Conditions</a> and <a href=\"#\">Privacy Policy</a></p>\r\n"
    		+ "                            </div>\r\n"
    		+ "                        </div>\r\n"
    		+ "                    </div>\r\n"
    		+ "                </div>\r\n"
    		+ "            </div>\r\n"
    		+ "<!-- //login -->\r\n"
    		+ "<a href=\"#home\" class=\"scroll\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\r\n"
    		+ "\r\n"
    		+ "<!-- js -->\r\n"
    		+ "<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n"
    		+ "<!-- //js -->\r\n"
    		+ "<script src=\"js/modernizr.custom.js\"></script>\r\n"
    		+ "    <!-- Custom-JavaScript-File-Links --> \r\n"
    		+ "    <!-- cart-js -->\r\n"
    		+ "    <script src=\"js/minicart.min.js\"></script>\r\n"
    		+ "<script>\r\n"
    		+ "    // Mini Cart\r\n"
    		+ "    paypal.minicart.render({\r\n"
    		+ "        action: '#'\r\n"
    		+ "    });\r\n"
    		+ "\r\n"
    		+ "    if (~window.location.search.indexOf('reset=true')) {\r\n"
    		+ "        paypal.minicart.reset();\r\n"
    		+ "    }\r\n"
    		+ "</script>\r\n"
    		+ "\r\n"
    		+ "    <!-- //cart-js --> \r\n"
    		+ "<!-- script for responsive tabs -->                     \r\n"
    		+ "<script src=\"js/easy-responsive-tabs.js\"></script>\r\n"
    		+ "<script>\r\n"
    		+ "    $(document).ready(function () {\r\n"
    		+ "    $('#horizontalTab').easyResponsiveTabs({\r\n"
    		+ "    type: 'default', //Types: default, vertical, accordion           \r\n"
    		+ "    width: 'auto', //auto or any width like 600px\r\n"
    		+ "    fit: true,   // 100% fit in a container\r\n"
    		+ "    closed: 'accordion', // Start closed if in accordion view\r\n"
    		+ "    activate: function(event) { // Callback function if tab is switched\r\n"
    		+ "    var $tab = $(this);\r\n"
    		+ "    var $info = $('#tabInfo');\r\n"
    		+ "    var $name = $('span', $info);\r\n"
    		+ "    $name.text($tab.text());\r\n"
    		+ "    $info.show();\r\n"
    		+ "    }\r\n"
    		+ "    });\r\n"
    		+ "    $('#verticalTab').easyResponsiveTabs({\r\n"
    		+ "    type: 'vertical',\r\n"
    		+ "    width: 'auto',\r\n"
    		+ "    fit: true\r\n"
    		+ "    });\r\n"
    		+ "    });\r\n"
    		+ "</script>\r\n"
    		+ "<!-- //script for responsive tabs -->       \r\n"
    		+ "<!-- stats -->\r\n"
    		+ "    <script src=\"js/jquery.waypoints.min.js\"></script>\r\n"
    		+ "    <script src=\"js/jquery.countup.js\"></script>\r\n"
    		+ "    <script>\r\n"
    		+ "        $('.counter').countUp();\r\n"
    		+ "    </script>\r\n"
    		+ "<!-- //stats -->\r\n"
    		+ "<!-- start-smoth-scrolling -->\r\n"
    		+ "<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n"
    		+ "<script type=\"text/javascript\" src=\"js/jquery.easing.min.js\"></script>\r\n"
    		+ "<script type=\"text/javascript\">\r\n"
    		+ "    jQuery(document).ready(function($) {\r\n"
    		+ "        $(\".scroll\").click(function(event){     \r\n"
    		+ "            event.preventDefault();\r\n"
    		+ "            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n"
    		+ "        });\r\n"
    		+ "    });\r\n"
    		+ "</script>\r\n"
    		+ "<!-- here stars scrolling icon -->\r\n"
    		+ "    <script type=\"text/javascript\">\r\n"
    		+ "        $(document).ready(function() {\r\n"
    		+ "            /*\r\n"
    		+ "                var defaults = {\r\n"
    		+ "                containerID: 'toTop', // fading element id\r\n"
    		+ "                containerHoverID: 'toTopHover', // fading element hover id\r\n"
    		+ "                scrollSpeed: 1200,\r\n"
    		+ "                easingType: 'linear' \r\n"
    		+ "                };\r\n"
    		+ "            */\r\n"
    		+ "                                \r\n"
    		+ "            $().UItoTop({ easingType: 'easeOutQuart' });\r\n"
    		+ "                                \r\n"
    		+ "            });\r\n"
    		+ "    </script>\r\n"
    		+ "<!-- //here ends scrolling icon -->\r\n"
    		+ "\r\n"
    		+ "<!-- for bootstrap working -->\r\n"
    		+ "<script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n"
    		+ "</body>\r\n"
    		+ "<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n"
    		+ "<script src=\"static/scripts/responses.js\"></script>\r\n"
    		+ "<script src=\"static/scripts/chat.js\"></script>\r\n"
    		+ "\r\n"
    		+ "</html>\r\n"
    		+ "");
    }}
    
    
        